ffmpeg recording tool: added dynamic monitor geometry extraction, change i3 to launch camera window in floating mode and cleaned up code

diff --git a/local-bin/.local/bin/camera-stream b/local-bin/.local/bin/camera-stream
--- a/local-bin/.local/bin/camera-stream
+++ b/local-bin/.local/bin/camera-stream
@@ -1,17 +1,49 @@
 #!/usr/bin/env bash
 
-# screen_w="$(xrandr | awk '/\*/ {print $1; exit}' | cut -d'x' -f1)"
-# screen_h="$(xrandr | awk '/\*/ {print $1; exit}' | cut -d'x' -f2)"
-screen_w="$(xrandr | awk '/HDMI/ {print $3; exit}' | cut -d'x' -f1)"
-screen_h="$(xrandr | awk '/HDMI/ {print $3; exit}' | cut -d'x' -f2 | cut -d'+' -f1)"
+extract_geometry() {
+	line="$(
+		xrandr --listmonitors |
+		awk '
+			NR == 1 {
+				count = $2
+				next
+			}
+			count >= 2 && $1 ~ /^1:/ { print; exit }
+			count < 2  && $1 ~ /^0:/ { print; exit }
+		'
+	)"
+	
+	if [[ -z "${line}" ]]; then
+		printf 'failed to determine monitor geometry\n' >&2
+		exit 1
+	fi
+	
+	geometry="$(awk '{ print $3 }' <<<"$line")"
+	
+	if [[ ! $geometry =~ ^([0-9]+)/[0-9]+x([0-9]+)/[0-9]+\+([0-9]+)\+([0-9]+)$ ]]; then
+		printf 'failed to parse geometry: %s\n' "$geometry" >&2
+		exit 1
+	fi
+	
+	width="${BASH_REMATCH[1]}"
+	height="${BASH_REMATCH[2]}"
+	x="${BASH_REMATCH[3]}"
+	y="${BASH_REMATCH[4]}"
+}
 
-win_w=$((screen_w / 9))
-win_h=$((screen_h / 9))
+extract_geometry
+win_w=$((width / 10))
+win_h=$((height / 10))
 
 # start the camera stream
 ffplay -loglevel -8 \
 	-f v4l2 \
+	-input_format mjpeg \
 	-framerate 30 \
+	-video_size 420x180 \
+	-fflags nobuffer \
+	-flags low_delay \
+	-framedrop \
+	-fast \
 	-vf hflip \
-	-x "$win_w" -y "$win_h" \
 	-i /dev/video0 >/dev/null 2>&1 &
diff --git a/local-bin/.local/bin/ffrecord b/local-bin/.local/bin/ffrecord
--- a/local-bin/.local/bin/ffrecord
+++ b/local-bin/.local/bin/ffrecord
@@ -11,14 +11,48 @@ notify() {
     notify-send "$1" "$2"
 }
 
+extract_geometry() {
+    line="$(
+    	xrandr --listmonitors |
+    	awk '
+    		NR == 1 {
+    			count = $2
+    			next
+    		}
+    		count >= 2 && $1 ~ /^1:/ { print; exit }
+    		count < 2  && $1 ~ /^0:/ { print; exit }
+    	'
+    )"
+    
+    if [[ -z "${line}" ]]; then
+    	printf 'failed to determine monitor geometry\n' >&2
+    	exit 1
+    fi
+    
+    geometry="$(awk '{ print $3 }' <<<"$line")"
+    
+    if [[ ! $geometry =~ ^([0-9]+)/[0-9]+x([0-9]+)/[0-9]+\+([0-9]+)\+([0-9]+)$ ]]; then
+    	printf 'failed to parse geometry: %s\n' "$geometry" >&2
+    	exit 1
+    fi
+    
+    width="${BASH_REMATCH[1]}"
+    height="${BASH_REMATCH[2]}"
+    x="${BASH_REMATCH[3]}"
+    y="${BASH_REMATCH[4]}"
+
+}
+
 start_recording() {
     local output
     output="${record_dir}/video-$(date '+%Y-%m-%d_%H_%M_%S').mp4"
+    extract_geometry
 
     nohup ffmpeg \
-        -s 1920x1080 \
+        -s "${width}"x"${height}" \
+	-framerate 30 \
         -f x11grab \
-        -i :0.0+1920,0 \
+        -i :0.0+"${x}",0 \
         -f alsa \
         -i default \
         -c:v libx264 \
