zsh: changed the copy to clipboard funciton name to y get-weather: added a feature to select a national weather map

diff --git a/local-bin/.local/bin/get-weather b/local-bin/.local/bin/get-weather
--- a/local-bin/.local/bin/get-weather
+++ b/local-bin/.local/bin/get-weather
@@ -1,8 +1,23 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-url='https://radar.weather.gov/ridge/standard/KDAX_loop.gif'
+url_local='https://radar.weather.gov/ridge/standard/KDAX_loop.gif'
+url_national='https://radar.weather.gov/ridge/standard/CONUS-LARGE_loop.gif'
 # url='https://s.w-x.co/staticmaps/wu/wu/radsum1200_cur/usbfl/animate.png'
 # url='https://cdn.star.nesdis.noaa.gov/GOES19/ABI/CONUS/GEOCOLOR/GOES19-CONUS-GEOCOLOR-625x375.gif'
-# url='https://radar.weather.gov/ridge/standard/CONUS-LARGE_loop.gif'
-curl -sL "$url" | mpv --loop-file=inf - >/dev/null 2>&1 &
+
+url="$url_local"
+
+case "${1-}" in
+	-n|--national)
+		url="$url_national"
+		;;
+	"")
+		;;
+	*)
+		printf 'error: unknown option: %s\n' "${1-}" >&2
+		exit 1
+		;;
+esac
+
+curl -fsSL "$url" 2>/dev/null | mpv --loop-file=inf - >/dev/null 2>&1 &
